### ISSUE TITLE
Winx64 version mount problem

### ISSUE THREAD

**Issue by Achim16** [netheril96/securefs#29]
Glad that you published a Win version, as I've no option to complie this myself, (therefore cannot test the x86 version). After having installed Winfsp RC2 and VC++15 I was able to create via securefs c a data dir without issues - fine. Mounting however doesn't work, securefs m j:\datadir w: still ends with a complaint that it mount path must be a drive letter. Has anything like that been reported already to you ? Would you assume it's more an Winfsp problem ? 
Thanks  
[edit : Win 7 x64 Ultimate]

**Comment by netheril96** [comment]
Uh, currently the drive letter must be in uppercase.

**Comment by netheril96** [comment]
It will fixed in a later revision.

**Comment by netheril96** [comment]
Fixed in 6680f4095e3c7d84e6e5adfc60991d6a710429f8. Of course, before it is released, you have to stick with uppercase drive letters only.

**Comment by Achim16** [comment]
Well, got a step further : 
Info] [00000000000013E4] [2017-02-16 22:27:11.916734200 UTC]    Mounting filesy
stem stored at j:\securefs onto A: with format version: 4
Cannot create WinFsp-FUSE file system: unspecified error.

More a winfsp related issue ?

**Comment by netheril96** [comment]
Maybe because A: is reserved for floppy disk? Just try Z: as I have tried.

**Comment by netheril96** [comment]
Do you encounter any further problems with securefs win64?

**Comment by Achim16** [comment]
The problem with the unspecified error persists. Before posting I , to be sure, also tried it of course with other drive letters (W:, M: etc as Z: is DVD for me) than the old floppy A:. As this was on W7 x64, I'll also do this on a Win 10 x64 PC at some point to see if this has sth to do with winfsp as such.
If possible could you please for the next release also issue a x86 version.
Thanks

**Comment by netheril96** [comment]
See this prerelease https://github.com/netheril96/securefs/releases/tag/0.7.1

You can also try if the passthrough filesystem that comes with WinFsp works. If that doesn't work either, it is a bug with WinFsp instead.

**Comment by Achim16** [comment]
ok, Win10x64 = success, Win7x86 = success.
The Win7x64 system failing already fails to create MemFS service, I'm investigating, status code seems to relate to winfsp driver signing.
So, nothing to do then with securefs. Can be closed from my point. thx

**Comment by Achim16** [comment]
For completeness, in case somebody else is affected, the issue related to WinFSP can be solved following the discussion on WinFSP's Issue #43 "WinFsp installer is not signed by Microsoft" - in essence Security update KB3033929 finally fixed it.

**Comment by Achim16** [comment]
I don't want to open a new issue for this, as mounting in general works now, but I discovered a minor issue I didn't notice when testing last week.
Like I wrote, it now works in general , however always not for the first time after system boot :
 
C:\securefs m --log j:\test.log --trace j:\securefs w:
Password:
[Trace] [000000000000103C] [2017-02-28 23:51:28.238936800 UTC]    Opening file o
n a NTFS volume
[Verbose] [000000000000103C] [2017-02-28 23:51:29.237338600 UTC]    Raising the
number of file descriptor limit to 65535
[Verbose] [000000000000103C] [2017-02-28 23:51:29.237338600 UTC]    Filesystem p
arameters: format version 4, block size 4096 (bytes), iv size 12 (bytes)
[Verbose] [000000000000103C] [2017-02-28 23:51:29.237338600 UTC]    Master key:
a5b0641fa4b98d243d4937cf87e1635f5c4bd6609cdbfe3b12c1a672230c6bd0b24f8ac5fa110215
f4c003552e37e5cb3019bd2ff2658f4865443d19a62451c51b6f34c55f6926e23de0db8804b866fe
d75e9b28cfe616aebc289b77f9a1bc89
Cannot create WinFsp-FUSE file system.
The service securefs has failed to start (Status=c0000002)

It makes no difference by the way if it's upper or lower case, the bug you fixed already.

Second time and all following work fine : 
C:\>securefs m --log j:\test2.log --trace j:\securefs w:
Password:
[Trace] [00000000000017EC] [2017-02-28 23:52:38.189458800 UTC]    Opening file o
n a NTFS volume
[Verbose] [00000000000017EC] [2017-02-28 23:52:39.172260500 UTC]    Raising the
number of file descriptor limit to 65535
[Verbose] [00000000000017EC] [2017-02-28 23:52:39.172260500 UTC]    Filesystem p
arameters: format version 4, block size 4096 (bytes), iv size 12 (bytes)
[Verbose] [00000000000017EC] [2017-02-28 23:52:39.172260500 UTC]    Master key:
a5b0641fa4b98d243d4937cf87e1635f5c4bd6609cdbfe3b12c1a672230c6bd0b24f8ac5fa110215
f4c003552e37e5cb3019bd2ff2658f4865443d19a62451c51b6f34c55f6926e23de0db8804b866fe
d75e9b28cfe616aebc289b77f9a1bc89
The service securefs has been started.
The service securefs has been stopped.

I enclose the log for the failing 1st timers after system boot :
[test.log.txt](https://github.com/netheril96/securefs/files/809341/test.log.txt)
and the one working one from wnd try afterwards :
[test2.log.txt](https://github.com/netheril96/securefs/files/809342/test2.log.txt)

**Comment by netheril96** [comment]
> Cannot create WinFsp-FUSE file system.
> The service securefs has failed to start (Status=c0000002)

This log comes from `WinFsp`. All I do is calling `fuse_main` provided by them at that point. So it is likely a problem with `WinFsp` again.

**Comment by netheril96** [comment]
It is likely a problem with `WinFsp` again. Have you tried the passthrough and memfs?
